### ISSUE TITLE
L.Map.Modal.HIDE never fired?

### ISSUE THREAD

**Issue by restani** [w8r/Leaflet.Modal#1]
I am having trouble seeing when the modal.hide event would be fired.

Maybe I am misunderstanding the design however. To me, when the user clicks away the modal, the modal.hide event should be fired, but that doesn't seem to be the case, since it seems to be missing a  css transition that would trigger a 'transitionend' event, calling _onTransitionEnd(), in turn firing the 'modal.hide' event.

Do you have any clue on why I'm not getting this modal.hide event? I'm using a really simple modal with simple html content and onHide, onShow handlers doing console.logs.

Great library btw!

**Comment by w8r** [comment]
@restani, thanks, let me check this one
